LOG:  database system was shut down at 2016-08-26 13:14:52 PDT
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
FATAL:  role "test" does not exist
FATAL:  role "test" does not exist
FATAL:  role "test" does not exist
FATAL:  database "du" does not exist
FATAL:  database "justinewinnie" does not exist
FATAL:  database "du" does not exist
FATAL:  database "u" does not exist
FATAL:  database "justinewinnie" does not exist
FATAL:  role "test" does not exist
FATAL:  database "justine" does not exist
FATAL:  database "callisto" does not exist
FATAL:  database "syncdb" does not exist
ERROR:  duplicate key value violates unique constraint "django_site_domain_a2e37b91_uniq"
DETAIL:  Key (domain)=(example.com) already exists.
STATEMENT:  INSERT INTO "django_site" ("domain", "name") VALUES ('example.com', 'example.com') RETURNING "django_site"."id"
